services:
    ds_re_captcha.validator:
        class: DS\Component\ReCaptchaValidator\Validator\ReCaptchaValidator
        arguments:
            - # Either @request or @request_stack
            - "%re_captcha.private_key%"
            - null
            - "%re_captcha.enabled%"
        tags:
            - { name: validator.constraint_validator, alias: ds_re_captcha.validator }

    ds_re_captcha.form.type:
        class: DS\Component\ReCaptchaValidator\Form\ReCaptchaType
        arguments: ["%re_captcha.public_key%", "%re_captcha.locale%"]
        tags:
            - { name: form.type, alias: ds_re_captcha }

